// #version 460 core
// #define POSTPROCESS
// #define USE_FOG_POST
// #define TH_Z_SLICES 15
// #define TH_Z_MEMORY 10
#define texture2D texture
// #extension GL_KHR_shader_subgroup_ballot : enable
layout(local_size_x = 8, local_size_y = 4) in;
//TODO use image format
layout(rgba16f, binding = 0) uniform image2D img_output;
layout(r16f, binding = 6) uniform image2D img_output_hitdist;

#define STOCHASTIC_TRUE
#define REALTIME_BDRF
#define USE_DIST_IN_CULL

// #define LOD_BIAS_QUICKLOOKUP 1.0
// #define LOD_BIAS 3.0
//#define CUBEMAP_FAST
// #define LOD_BIAS_QUICKLOOKUP 1.0
// #define LOD_BIAS 3.0

layout(binding=0) uniform sampler2D texInfo;
layout(binding=4) uniform sampler2D brdfLUT;
layout(binding=3) uniform sampler2D norInfo;
layout(binding=2) uniform sampler2D depthTex;
layout(binding=1) uniform sampler2D normalTex;
layout(binding=22) uniform samplerCubeArray reflections;
layout(binding=21) uniform samplerCubeArray reflectionsDepth;
layout(binding=23) uniform samplerCube atmosphereCube;
layout(binding=5) uniform sampler2D texCoordTex;
layout(binding=25) uniform sampler2D noiseTex;
layout(binding=27) uniform sampler2D old_reflectiondata;
layout(binding=28) uniform sampler2D old_depthtexture;
layout(binding=30) uniform sampler2D oldnormalTex;

uniform mat4 old_mvp;
uniform mat4 projMatrixInv_old;
uniform mat4 viewMatrixInv_old;


uniform mat4 projMatrixInv;
uniform mat4 viewMatrixInv;
uniform vec3 eyePos;
uniform vec2 screenSize;
uniform mat4 viewMat;
uniform mat4 projMat;
uniform uint frame;

uniform float cube_nohit_sky = 1.0;
uniform float zNear = 0.1;
uniform float zFar = 1000;
uint num_tiles_x = 16;
uint num_tiles_y = 8;
uint num_slices = TH_Z_SLICES;
const float PI = 3.14159265359;
const float MAX_TRACE = 5000.0;

layout (std140 , binding = 0) uniform EnvBoxes
{
  vec4 EnvBoxPos[55];// 0
  vec4 EnvBoxMin[55];// size*16
  vec4 EnvBoxMax[55];//size * 16*2
  int EnvBoxCount;//size*16*3
  //total size is size*16*3 + 4
};

layout (std140 , binding = 5) uniform Access_Buffer_CUBES //
{
  uniform uvec4 acessbuffercubes[4096];//use the max amount of memory
};

layout (std140 , binding = 4) uniform Offsets_buffer_CUBES //size of grid
{
  uniform uvec4 offsets[(16*8*TH_Z_MEMORY)];//pack into vec4 for std140
};

layout (std430 , binding = 0) restrict readonly buffer BlueNoise //size of grid
{
   uint g_scrambling_tile_buffer[128*128*8];
};


vec2 when_ge2(vec2 x, vec2 y) {
  return 1.0 - max(sign(y - x), 0.0);
}
vec3 decodeNormal( vec2 f )
{
    f = f * 2.0 - 1.0;
    vec3 n = vec3( f.x, f.y, 1.0 - abs( f.x ) - abs( f.y ) );
    float t = clamp( -n.z,0,1 );
    n.xy += -sign(when_ge2(n.xy,vec2(0)) - vec2(0.5))*t;
    return normalize( n );
}

vec3 WorldPosFromDepth(vec2 outTexcoord,float depth,out vec4 viewSpacePosition2) {
  float z = depth * 2.0 - 1.0;

  vec4 clipSpacePosition = vec4(outTexcoord * 2.0 - 1.0, z, 1.0);
  vec4 viewSpacePosition = projMatrixInv * clipSpacePosition;

  // Perspective division
  viewSpacePosition /= viewSpacePosition.w;
  viewSpacePosition2 = viewSpacePosition;

  vec4 worldSpacePosition = viewMatrixInv * viewSpacePosition;

  return worldSpacePosition.xyz;
}


float not(float a) {
  return 1.0 - a;
}

float or(float a, float b) {
  return min(a + b, 1.0);
}

float when_eq(float x, float y) {
  return  1- abs(sign(x - y));
}

float when_gt(float x, float y) {
  return max(sign(x - y), 0.0);
}

float when_lt(float x, float y) {
  return max(sign(y - x), 0.0);
}


float when_ge(float x, float y) {
  return 1.0 - max(sign(y - x), 0.0);
}


float distance_squared(vec3 a,vec3 b)
{
  vec3 d = a -b;
  return dot(d,d);
}





float raymarch(vec3 worldspaceRay,vec3 worldSpaceDirection,float cubeindex,vec3 cubepos,out vec3 result,out float dist_to_hit,int iterations,int steps,float synflag)
{
  float REFDEPTH_LEVEL  = LOD_BIAS;//4.0f;

  vec3 worldSpaceRay = worldspaceRay;
  float depth = 0;
  vec3 minp = vec3(worldspaceRay);
  vec3 maxp = vec3(worldspaceRay +worldSpaceDirection*MAX_TRACE );
  float hit = 0;

  float delta = MAX_TRACE/steps;
  //delta*2
  depth += delta*2*synflag;//*synflag;
  //depth += delta; //needed for lower resolution mips
  //constant angle sampling, not used
  // vec3 start = normalize((worldspaceRay +worldSpaceDirection*2 - cubepos));
  // vec3 end = normalize((worldspaceRay +worldSpaceDirection*2000 - cubepos));
  // float theta_total = acos(dot(start,end));
  // float theta_delta = theta_total/steps;



  for (int i = 0; i < steps; i+=4) {

    vec3 p_0 = worldspaceRay + worldSpaceDirection*depth;
    vec3 p_1 = worldspaceRay + worldSpaceDirection*(depth + delta*1);
    vec3 p_2 = worldspaceRay + worldSpaceDirection*(depth + delta*2);
    vec3 p_3 = worldspaceRay + worldSpaceDirection*(depth + delta*3);

    maxp = p_3;
    float dist_0 = textureLod(reflectionsDepth, vec4((p_0 - cubepos)*vec3(-1,1,1),cubeindex),REFDEPTH_LEVEL).r;
    float dist_1 = textureLod(reflectionsDepth, vec4((p_1 - cubepos)*vec3(-1,1,1),cubeindex),REFDEPTH_LEVEL).r;
    float dist_2 = textureLod(reflectionsDepth, vec4((p_2 - cubepos)*vec3(-1,1,1),cubeindex),REFDEPTH_LEVEL).r;
    float dist_3 = textureLod(reflectionsDepth, vec4((p_3 - cubepos)*vec3(-1,1,1),cubeindex),REFDEPTH_LEVEL).r;


    // float cond_0 = when_lt(dist_0*dist_0,distance_squared(p_0,cubepos));
    // float cond_1 = when_lt(dist_1*dist_1,distance_squared(p_1,cubepos));
    // float cond_2 = when_lt(dist_2*dist_2,distance_squared(p_2,cubepos));
    // float cond_3 = when_lt(dist_3*dist_3,distance_squared(p_3,cubepos));
    if (dist_0*dist_0 < distance_squared(p_0,cubepos) || dist_1*dist_1 < distance_squared(p_1,cubepos) || dist_2*dist_2 < distance_squared(p_2,cubepos) || dist_3*dist_3 < distance_squared(p_3,cubepos))
    {
      float d0_hit = when_lt(dist_0*dist_0 , distance_squared(p_0,cubepos));
      float d1_hit = when_lt(dist_1*dist_1 , distance_squared(p_1,cubepos));
      float d2_hit = when_lt(dist_2*dist_2 , distance_squared(p_2,cubepos));
      float d3_hit = when_lt(dist_3*dist_3 , distance_squared(p_3,cubepos));
      maxp = p_0*(d0_hit) + p_1*(d1_hit*(1 - d0_hit)) + p_2*(d2_hit*(1 - d0_hit)*(1 - d1_hit)) + p_3*(d3_hit*(1 - d0_hit)*(1 - d1_hit)*(1 - d2_hit));
      minp = maxp - worldSpaceDirection*(delta);

      hit = 1;
      break;
    }
    minp = p_3;
    depth += delta*4;

    // uint active_threads = subgroupBallotBitCount(subgroupBallot(true));
    // if (active_threads < 16)
    // {
    //   break;
    // }
  }
  //binary search
  //refines by delta*0.5^iterations
  vec3 mid = vec3(0);
  float dist3 = 0;
  float dist2 = 0;
  float d2 = 0;
  if (hit == 1)
  {
    for (int i = 0 ; i < iterations;i++)
    {
      mid = (maxp + minp)*vec3(0.5);
      dist3 = textureLod(reflectionsDepth, vec4((mid - cubepos)*vec3(-1,1,1),cubeindex),REFDEPTH_LEVEL).r;
      float dist2 = dist3*dist3;
      float d2 = distance_squared(mid,cubepos);
      float cmp = when_lt(dist2,d2);

      maxp = maxp*(1-cmp) + cmp*mid;
      minp = mid*(1-cmp) + cmp*minp;

    }
  }

  hit *= 1 - when_gt(abs(dist3 - distance(mid,cubepos)),MAX_TRACE);


  mid = (maxp + minp)*vec3(0.5);
  vec3 intersection = mid;//worldspaceRay + worldSpaceDirection * depth;
  result =  intersection - cubepos;
  float dist = textureLod(reflectionsDepth, vec4((result)*vec3(-1,1,1),cubeindex),REFDEPTH_LEVEL).r;
  hit = hit*when_lt(dist,MAX_TRACE);//when_lt(dist*dist,distance_squared(maxp,cubepos));


  result = result*hit + (1-hit)*worldSpaceDirection;

  dist_to_hit = distance(worldSpaceRay,intersection)*(hit);// + 0*(1-1);
  return hit;
}


float CheckCollision(vec3 pos, vec3 bmin,vec3 bmax)
{
  return when_lt(pos.x,bmax.x)*when_lt(pos.y,bmax.y)*when_lt(pos.z,bmax.z)*when_gt(pos.x,bmin.x)*when_gt(pos.y,bmin.y)*when_gt(pos.z,bmin.z);
}


vec3 fresnelSchlick(float cosTheta, vec3 F0,float roughness)
{
  return F0 + (max(vec3(1.0 - roughness), F0) - F0) * pow(1.0 - cosTheta, 5.0);
}


float screen2EyeDepth(float depth, float near, float far)
{

    float ndc = 2.0 * depth - 1.0;
    float eye = 2.0 * far * near / (far + near + ndc * (near - far));
    return eye;
}

// uint getClusterZIndex(float screenDepth)
// {
//
//     float eyeDepth = screen2EyeDepth(screenDepth, zNear, zFar);
//     uint zIndex = uint(float(num_slices)*(log(eyeDepth/zNear)/log(zFar/zNear)));
//     // uint zIndex = uint(max(log(eyeDepth) * scale + bias, 0.0));
//     return zIndex;
// }

uint getClusterZIndex(float screenDepth)
{

  float eyeDepth = screen2EyeDepth(screenDepth, zNear, zFar);
  eyeDepth = clamp(eyeDepth, zNear, zFar);
  uint zIndex = max(int( max(0,float(num_slices)*(log((eyeDepth/zNear))/log(zFar/zNear)) ) ) - 5,0);
  // uint zIndex = uint(max(log(eyeDepth) * scale + bias, 0.0));
  return zIndex;
}


//sampling the distribution of visible normals
//https://jcgt.org/published/0007/04/01/
vec3 SampleGGXVNDF(vec3 Ve, float alpha_x, float alpha_y, float U1, float U2) {
    // Section 3.2: transforming the view direction to the hemisphere configuration
    vec3 Vh = normalize(vec3(alpha_x * Ve.x, alpha_y * Ve.y, Ve.z));
    // Section 4.1: orthonormal basis (with special case if cross product is zero)
    float lensq = Vh.x * Vh.x + Vh.y * Vh.y;
    vec3 T1 = lensq > 0 ? vec3(-Vh.y, Vh.x, 0) * inversesqrt(lensq) : vec3(1, 0, 0);
    vec3 T2 = cross(Vh, T1);
    // Section 4.2: parameterization of the projected area
    float r = sqrt(U1);
    float phi = 2.0 * PI * U2;
    float t1 = r * cos(phi);
    float t2 = r * sin(phi);
    float s = 0.5 * (1.0 + Vh.z);
    t2 = (1.0 - s) * sqrt(1.0 - t1 * t1) + s * t2;
    // Section 4.3: reprojection onto hemisphere
    vec3 Nh = t1 * T1 + t2 * T2 + sqrt(max(0.0, 1.0 - t1 * t1 - t2 * t2)) * Vh;
    // Section 3.4: transforming the normal back to the ellipsoid configuration
    vec3 Ne = normalize(vec3(alpha_x * Nh.x, alpha_y * Nh.y, max(0.0, Nh.z)));
    return Ne;
}

mat3 CreateTBN(vec3 N) {
    vec3 U;
    float fac = when_gt(abs(N.z) , 0.0);
    float a = N.z*fac + N.x*(1-fac);
    float k = sqrt(a * a + N.y*N.y);
    U.x = (N.y/k)*(1.0 - fac);
    U.y = (-N.z / k)*fac + (-N.x / k)*(1-fac);
    U.z = (N.y / k)*fac;

    mat3 TBN;
    TBN[0] = U;
    TBN[1] = cross(N, U);
    TBN[2] = N;
    return (TBN);
}



vec3 SampleReflectionVector(vec3 view_direction, vec3 normal, float roughness, vec2 u,out vec3 microsurface_normal) {
    mat3 inv_tbn_transform = CreateTBN(normal);
    mat3 tbn_transform = transpose(inv_tbn_transform);

    vec3 view_direction_tbn = tbn_transform*-view_direction;

    float roughness2 = roughness*roughness;
    vec3 sampled_normal_tbn = SampleGGXVNDF(view_direction_tbn, roughness2,roughness2, u.x, u.y);


    vec3 reflected_direction_tbn = reflect(-view_direction_tbn, sampled_normal_tbn);

    // Transform reflected_direction back to the initial space.
    microsurface_normal = inv_tbn_transform*sampled_normal_tbn;
    return  inv_tbn_transform*reflected_direction_tbn;
}

// Blue Noise Sampler by Eric Heitz. Returns a value in the range [0, 1].
float SampleRandomNumber(uint pixel_i, uint pixel_j, uint sample_index, float sample_dimension) {
    // Wrap arguments
    pixel_i = pixel_i & 127u;
    pixel_j = pixel_j & 127u;
    // sample_index = sample_index & 255u;
    // sample_dimension = sample_dimension & 255u;

    const uint ranked_sample_index = sample_index ^ 0;


    // Fetch value in sequence
    uint value = uint(32.0*(1.0-float(sample_dimension)) + 226.0*float(sample_dimension));//g_sobol_buffer[sample_dimension + ranked_sample_index * 256u];

    // // If the dimension is optimized, xor sequence value based on optimized scrambling
    value = value ^ g_scrambling_tile_buffer[(uint(sample_dimension) ) + (pixel_i + pixel_j * 128u)*8u ];//

    // Convert to float and return
    return (float(value) + 0.5) / 256.0f;
}

vec2 SampleRandomVector2D(uvec2 pixel,uint offset) {
    vec2 u = vec2(
        mod(SampleRandomNumber(pixel.x, pixel.y, 0, 0.0) + float((uint(frame) + offset) & 0xFFu) * 1.61803398875f, 1.0f),
        mod(SampleRandomNumber(pixel.x, pixel.y, 0, 1.0) + float((uint(frame) + offset) & 0xFFu) * 1.61803398875f, 1.0f));
    return u;
}

vec2 values[9] = {vec2(-1,0),vec2(1,0),vec2(-1,1),vec2(1,1),vec2(-1,-1),vec2(1,-1),vec2(0,-1),vec2(0,1),vec2(0,0)};



//G1 is smith shadowing

//G2 is shadowing and masking


float BsdfNDot(vec3 a,vec3 b)
{
  return max(dot(a, b), 0.0);
}
float SmithGGXMasking(vec3 N,vec3 V,vec3 L, float a2)
{
    float dotNL = BsdfNDot(N,L);
    float dotNV = BsdfNDot(N,V);
    float denomC = sqrt(a2 + (1.0f - a2) * dotNV * dotNV) + dotNV;
    float mask = 2.0f * dotNV / max(denomC,0.0001);
    return mask*when_gt(denomC,0.0);
}

//====================================================================
float SmithGGXMaskingShadowing(vec3 N,vec3 V,vec3 L,  float a2)
{
  float dotNL = BsdfNDot(N,L);
  float dotNV = BsdfNDot(N,V);

    float denomA = dotNV * sqrt(a2 + (1.0f - a2) * dotNL * dotNL);
    float denomB = dotNL * sqrt(a2 + (1.0f - a2) * dotNV * dotNV);

    return 2.0f * dotNL * dotNV / max(denomA + denomB,0.00001);
}
 vec3 SchlickFresnel(vec3 r0, float rad)
{
    // -- The common Schlick Fresnel approximation
    float exponential = pow(1.0f - rad, 5.0f);
    return r0 + (1.0f - r0) * exponential;
}


vec4 traceCubes(uvec2 pixel_id,float depthval,vec3 position,vec3 normal,vec3 refnormal,float roughness,vec3 viewDir,float metal,int quality,vec3 F0,vec3 brdf,float synflag)
{
  float alpha = 1;
  float index = -1;
  float bounded = 0;//CheckCollision(position,EnvBoxMin[0],EnvBoxMax[0]);
  float cur_dist = -1;
  float closest_probe = 0;
  //float dist_2 = 1.0/0.0;//infinity :)

  ivec2 tile_id = ivec2((pixel_id.xy + 0.5/screenSize ) / vec2(screenSize.x/16.0,screenSize.y/8.0));
  uint cluster_slice_id = getClusterZIndex(depthval);

  uint tile_index = tile_id.x + tile_id.y*num_tiles_x + cluster_slice_id*num_tiles_x*num_tiles_y;

  uvec2 arr[2];
  arr[0] = offsets[tile_index/2 + (16*8*TH_Z_MEMORY)/2].xy;
  arr[1] = offsets[tile_index/2 + (16*8*TH_Z_MEMORY)/2].zw;
  uint count = arr[tile_index%2].y;
  uint offset = arr[tile_index%2].x;
  float fastNdotL = uintBitsToFloat(packHalf2x16(vec2(-1 ,1)));//dot(normal,refnormal);

    // return vec4(0,0,0,0);
  if (count ==0)
  {
    //outside simulation domain
    #ifdef STOCHASTIC_TRUE
    vec4 lookup_fast = textureLod(atmosphereCube,(refnormal*vec3(-1,1,1)),roughness*4.0);

    return vec4(lookup_fast.xyz*brdf,uintBitsToFloat(packHalf2x16(vec2(-1 ,-1))));
    #else
    vec4 lookup_fast = textureLod(atmosphereCube,(refnormal*vec3(-1,1,1)),roughness*4.0);

    return vec4(lookup_fast.xyz,fastNdotL);
    #endif

  }

  //smaller offset 10
  vec3 offsetpos = position + normal*10*synflag;//maybe use geormetry normal instead of normal mapped
//  vec3 position_bias = position + normal*100*synflag;//maybe use geormetry normal instead of normal mapped

  #ifdef USE_DIST_IN_CULL
  float dist_texs[32];
  float lod_defdepth_quicklookup = LOD_BIAS_QUICKLOOKUP;
  // float bias_quicklookup = -100;
    // float bias_quicklookup = -100;
    float bias_quicklookup = -10;
  for (int i = 0 ; i < count;i++)
  {
    uint a = offset + i;
    uint key =  acessbuffercubes[a/4][a%4];
    dist_texs[i] = textureLod(reflectionsDepth, vec4(normalize(offsetpos - EnvBoxPos[key].xyz)*vec3(-1,1,1),key),lod_defdepth_quicklookup).r;
  }
  #endif

  for (int i = 0 ; i < count;i++)
  {
    uint a = offset + i;
    uint key =  acessbuffercubes[a/4][a%4];

    #ifdef USE_DIST_IN_CULL
    float dist_tex = dist_texs[i];//textureLod(reflectionsDepth, vec4(normalize(offsetpos - EnvBoxPos[key])*vec3(-1,1,1),key),5.0).r;
    float cond = when_gt((dist_tex - sqrt(distance_squared(offsetpos,EnvBoxPos[key].xyz) ) ),bias_quicklookup);
    #else
    float cond = 1.0;
    #endif

    float factor_normal = when_gt(dot((EnvBoxPos[key].xyz - position),normal),0);
    //float bounded_i = cond*CheckCollision(position,EnvBoxMin[key] + vec3(100),EnvBoxMax[key] -vec3(100))*(factor_normal*synflag + (1.0-synflag));
    float bounded_i = cond*CheckCollision(position,EnvBoxMin[key].xyz + vec3(100),EnvBoxMax[key].xyz -vec3(100));//*(factor_normal*synflag + (1.0-synflag));
    float dist = distance_squared(position,EnvBoxPos[key].xyz);

    float replace = or(when_eq(index,-1),(1-when_eq(index,-1))*when_lt(dist,cur_dist) )*bounded_i;
    index = replace*key + (1-replace)*index;
    cur_dist = cur_dist*(1-replace) + dist*replace;//distance_squared(position,EnvBoxPos[int(index)]);

  }
  if (index == -1)
  {
    //no suitable cubemap
  //  vec4 lookup_fast = textureLod(atmosphereCube,(refnormal*vec3(-1,1,1)),roughness*4.0);
    return vec4(0,0,0,0);

  }


  #ifdef CUBEMAP_FAST
  vec4 lookup_fast = textureLod(reflections,vec4(refnormal*vec3(-1,1,1),index),roughness*4.0);
  //textureLod(reflections,vec4(refnormal*vec3(-1,1,1),index),roughness*4.0);//
  return vec4(lookup_fast.xyz*brdf,uintBitsToFloat(packHalf2x16(vec2(-1 ,-1))));
  #endif


  float dist_to_hit = 0;
  float occ = 1;

  vec3 l;

  #ifdef REALTIME_BDRF

  float metalfactor = 0;//when_eq(metal,0)*when_gt(roughness,0.5);

  const uint sample_count = 30 ;//+ uint(when_gt(roughness,0.2))*31;//uint(clamp(roughness*3,1,2));
  vec3 accum = vec3(0);
  float total_weight = 0;
  vec4 lookup;
  float h = 0;
  // roughness = 0.5;
  vec3 lu;


  float NdotL = -1;
  int iterations = 0;
  vec3 L;

  vec2 Xi = SampleRandomVector2D(uvec2(pixel_id.xy),iterations);//Hammersley(uint(noise*939) , 1001 );
  Xi.x = mix(Xi.x,0.0,0.2);
  if (roughness < 0.1)
  {
    Xi = vec2(0,0);
  }

  //vec3 H = ImportanceSampleGGX(Xi, normal, roughness);
  vec3 microsurface_normal = vec3(0);
  L =  -SampleReflectionVector(viewDir,normal,roughness,Xi,microsurface_normal);
  L = normalize(L);
  // L  = -reflect(viewDir, H);
  NdotL = dot(normal, -L);
  // iterations++;

  NdotL = max(NdotL,0);

  //  float coarse = raymarchCoarse(position,-L,reflectionsDepth,index,EnvBoxPos[int(index)]);
  vec4 lookup2;
  //  L = L*(1-metalfactor) + metalfactor*-refnormal;


  // int iters[] = {6,4,6};
  // int steps[] = {8,17,28};

  int iters[] = {6,4,6};
  int steps[] = {8,17,30};
  float h2 = raymarch(position,-L,index,EnvBoxPos[int(index)].xyz,lu,dist_to_hit,iters[quality - 1],steps[quality -1],synflag);//Hit((position - EnvBoxPos[int(index)]), refnormal, reflectionsDepth,index); // ray hit
  h2 = or(h2,when_lt(roughness,0.1)*(1 - synflag));


  //float cone = clamp(dist_to_hit/500,0,1)*roughness*roughness;
  lookup2 = textureLod(reflections,vec4(lu*vec3(-1,1,1),index),0.0);

  lookup2 = lookup2*h2 + textureLod(atmosphereCube,(-L*vec3(-1,1,1)),roughness*0.0)*(1-h2)*cube_nohit_sky;

  h = clamp(h + h2,0,1);

  #ifdef STOCHASTIC_TRUE
  NdotL = NdotL*(h2);// + (1-h2)*1;

  vec3 N_b = normal;//use this
  vec3 L_b = -L;
  vec3 V_b = -viewDir;
  vec3 H_b = normalize(V_b + L_b);

  vec3 F = SchlickFresnel(F0, max(dot( V_b, normalize(microsurface_normal) ),0.0));
  float G1 = SmithGGXMasking(N_b,V_b,L_b, roughness*roughness);
  float G2 = SmithGGXMaskingShadowing(N_b,V_b,L_b,  roughness*roughness);

  //0.8 is the normalization factor
  vec3 reflectance = F *(G2 / max(G1,0.00001))*0.8;

  accum += lookup2.xyz*reflectance*when_gt(G1,0.000)*when_gt(dot(N_b,L_b),0.00);//*brdfweight;//*NdotL*when_gt(NdotL,0);//*(NdotL)*when_gt(NdotL,0);
  total_weight += 1*when_gt(dot(N_b,L_b),0.00);//brdfweight;//NdotL*when_gt(NdotL,0);

  #else
  NdotL = NdotL*(h2) + (1-h2)*1;
  accum += lookup2.xyz*(NdotL)*when_gt(NdotL,0);
  total_weight += NdotL*when_gt(NdotL,0);
  #endif

  lookup.xyz = (accum)*when_gt(total_weight,0);
  alpha = uintBitsToFloat(packHalf2x16(vec2(dist_to_hit,total_weight)))*h2 + fastNdotL*(1 - h2) ;


  #elif defined(FASTCUBES)
  vec4 lookup = textureLod(reflections,vec4(refnormal*vec3(-1,1,1),index),roughness*4.0);//
  alpha = fastNdotL;
  #else
  float h = raymarch(position,refnormal,reflectionsDepth,index,EnvBoxPos[int(index)].xyz,l,dist_to_hit,synflag);

  vec4 lookup = textureLod(reflections,vec4(l*vec3(-1,1,1),index),roughness*4.0);
  // lookup = vec4(l,0);
  lookup = lookup*h + textureLod(atmosphereCube,(l*vec3(-1,1,1)),roughness*4.0)*(1-h);
  #endif


  return vec4(lookup.xyz*occ,alpha);
}

// void main() {
//   // base pixel colour for image
//   vec4 pixel = vec4(0.0, 0.0, 0.0, 1.0);
//   // get index in global work group i.e x,y position
//   ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
//
//   //
//   // interesting stuff happens here later
//   //
//
//   // output to a specific pixel in the image
//   imageStore(img_output, pixel_coords, pixel);
// }

uvec2 ThreadGroupTilingX(
	const uvec2 dipatchGridDim,		// Arguments of the Dispatch call (typically from a ConstantBuffer)
	const uvec2 ctaDim,			// Already known in HLSL, eg:[numthreads(8, 8, 1)] -> uint2(8, 8)
	const uint maxTileWidth,		// User parameter (N). Recommended values: 8, 16 or 32.
	const uvec2 groupThreadID,		// SV_GroupThreadID
	const uvec2 groupId			// SV_GroupID
)
{
	// A perfect tile is one with dimensions = [maxTileWidth, dipatchGridDim.y]
	const uint Number_of_CTAs_in_a_perfect_tile = maxTileWidth * dipatchGridDim.y;

	// Possible number of perfect tiles
	const uint Number_of_perfect_tiles = dipatchGridDim.x / maxTileWidth;

	// Total number of CTAs present in the perfect tiles
	const uint Total_CTAs_in_all_perfect_tiles = Number_of_perfect_tiles * maxTileWidth * dipatchGridDim.y;
	const uint vThreadGroupIDFlattened = dipatchGridDim.x * groupId.y + groupId.x;

	// Tile_ID_of_current_CTA : current CTA to TILE-ID mapping.
	const uint Tile_ID_of_current_CTA = vThreadGroupIDFlattened / Number_of_CTAs_in_a_perfect_tile;
	const uint Local_CTA_ID_within_current_tile = vThreadGroupIDFlattened % Number_of_CTAs_in_a_perfect_tile;
	uint Local_CTA_ID_y_within_current_tile;
	uint Local_CTA_ID_x_within_current_tile;

	if (Total_CTAs_in_all_perfect_tiles <= vThreadGroupIDFlattened)
	{
		// Path taken only if the last tile has imperfect dimensions and CTAs from the last tile are launched.
		uint X_dimension_of_last_tile = dipatchGridDim.x % maxTileWidth;
	#ifdef DXC_STATIC_DISPATCH_GRID_DIM
		X_dimension_of_last_tile = max(1, X_dimension_of_last_tile);
	#endif
		Local_CTA_ID_y_within_current_tile = Local_CTA_ID_within_current_tile / X_dimension_of_last_tile;
		Local_CTA_ID_x_within_current_tile = Local_CTA_ID_within_current_tile % X_dimension_of_last_tile;
	}
	else
	{
		Local_CTA_ID_y_within_current_tile = Local_CTA_ID_within_current_tile / maxTileWidth;
		Local_CTA_ID_x_within_current_tile = Local_CTA_ID_within_current_tile % maxTileWidth;
	}

	const uint Swizzled_vThreadGroupIDFlattened =
		Tile_ID_of_current_CTA * maxTileWidth +
		Local_CTA_ID_y_within_current_tile * dipatchGridDim.x +
		Local_CTA_ID_x_within_current_tile;

	uvec2 SwizzledvThreadGroupID;
	SwizzledvThreadGroupID.y = Swizzled_vThreadGroupIDFlattened / dipatchGridDim.x;
	SwizzledvThreadGroupID.x = Swizzled_vThreadGroupIDFlattened % dipatchGridDim.x;

	uvec2 SwizzledvThreadID;
	SwizzledvThreadID.x = ctaDim.x * SwizzledvThreadGroupID.x + groupThreadID.x;
	SwizzledvThreadID.y = ctaDim.y * SwizzledvThreadGroupID.y + groupThreadID.y;

	return SwizzledvThreadID.xy;
}

float encodeFlags(int flags) {
  flags = clamp(flags, 0, 256);
  return float(flags/255.0);
}

int decodeFlags(float f) {
  // add 0.5 to avoid rounding errors from float
  return int(f*255.0 + 0.5);
}

float setFlag(float f, int bit) {
  int flags = decodeFlags(f);
  flags |= (1 << bit);
  return float(flags);
}

float setFlagConditional(float f, int bit,float val) {
  int flags = decodeFlags(f);
  flags |= (int(val) << bit);
  return float(flags);
}

float hasFlag(float f, int bit) {
  int flags = decodeFlags(f);
  return float((flags & (1 << bit)) != 0);
}

void main()
{
  // vec3 N_prime = decodeNormal(texture(norInfo,outTexcoord).zw);

  uvec2 global_invoc = ThreadGroupTilingX(uvec2((screenSize.x)/8,(screenSize.y)/4),uvec2(8,4),16,gl_LocalInvocationID.xy,gl_WorkGroupID.xy);

  ivec2 pixel_coords = ivec2(global_invoc.xy);
  vec2 outTexcoord = vec2(pixel_coords)/screenSize + 0.5/screenSize ;

  // vec3 ti = texture(texInfo,outTexcoord).xyz;
  float synflag = 1;//clamp( 1 - sign(ti.z),0,1);

  float depthval = texture2D(depthTex,outTexcoord ).r;
  vec4 viewSpacePosition;
  vec3 position = WorldPosFromDepth(outTexcoord,depthval,viewSpacePosition);

  // vec3 dx = dFdx(position);
  // vec3 dy = dFdy(position);
  // vec3 flatnormal = normalize(cross(dx,dy));


  vec3 viewDir    = normalize(position - eyePos);
  vec4 ntlookup = texture(normalTex,outTexcoord);
  vec3 normalt = ntlookup.xyz;
  synflag = 1 - hasFlag(ntlookup.w,0);
  vec3 normal = decodeNormal(normalt.xy);

  vec3 refnormal = reflect(viewDir,normal);
  float roughness = normalt.z;

  vec4 a = texture(texCoordTex, outTexcoord);
  float metallic  = a.a;
  vec3 albedo     = pow(a.rgb,vec3(2.2));

  //used for skybox fallback when outside simulation domain
  vec3 F0 = vec3(0.04);
  F0 = mix(F0, albedo, metallic);
  vec2 brdf  = texture(brdfLUT, vec2(max(dot(normal, -viewDir), 0.0), roughness)).rg;
  vec3 F = fresnelSchlick(max(dot(normal, -viewDir), 0.0), F0, roughness);


  vec3 val  = F*brdf.x + brdf.y;

  float dist_2 = distance_squared(eyePos,position);
  //dynamic quality scaling, disabled
  // float lv = when_lt(dist_2,200*200) + when_lt(dist_2,600*600) + 1;
  //
  // int quality = int(lv);
  int quality = 3;

//  fragColor = vec4(normal*0.5 + 0.5,uintBitsToFloat(packHalf2x16(vec2(0,1))));
  // int lv = textureQueryLevels(reflectionsDepth);
  // if (lv == 3)
  // {
  //   imageStore(img_output, pixel_coords, vec4(1,0,0,uintBitsToFloat(packHalf2x16(vec2(-1 ,-1)))));
  // }

  if (metallic < 0.5 && roughness > 0.9 )
  {
    imageStore(img_output, pixel_coords, vec4(0,0,0,1));
    imageStore(img_output_hitdist, pixel_coords, vec4(0.0));
  }
  else
  {
    vec4 pixel =  traceCubes( global_invoc,depthval, position, normal, refnormal, roughness,viewDir,metallic,quality,F0,val,synflag);
    float pixel_hit_dist = unpackHalf2x16(floatBitsToUint(pixel.w)).x;
    float pixel_weight = unpackHalf2x16(floatBitsToUint(pixel.w)).y;
    imageStore(img_output, pixel_coords, vec4(pixel.xyz,pixel_weight));
    imageStore(img_output_hitdist, pixel_coords, vec4(pixel_hit_dist,0,0,0));
  }
}
