#version 460 core
// #extension GL_NV_compute_shader_derivatives : enable
#define GROUP_SIZE_x 8
#define GROUP_SIZE_y 4
layout(local_size_x = GROUP_SIZE_x, local_size_y = GROUP_SIZE_y,local_size_z = 1) in;


layout(rgba8, binding = 1) uniform image2D normalroughness_img;
layout(rgba8, binding = 2) uniform image2D albedometal_img;

layout(binding=0) uniform sampler2D texInfo;
layout(binding=2) uniform sampler2D depthTex;
layout(binding=3) uniform sampler2D norInfo;

layout(binding=6) uniform sampler2DArray materials;
//#define MIX_NORMALS
//#define BLUE_NOISE

uniform mat4 projMatrixInv;
uniform mat4 viewMatrixInv;
uniform vec2 screenSize;
// uniform int materialProperties[1024];

uniform float zNear = 0.1;
uniform float zFar = 1000;
uint num_tiles_x = 16;
uint num_tiles_y = 8;
uint num_slices = 20;

struct Decal
{
  mat4 decal_matrix;//0 - 64
  vec4 decal_properties;//64-80
};

layout (std140 , binding = 7) uniform Decals
{
  uniform Decal decals_list[800];
};

layout (std140 , binding = 8) uniform Access_Buffer_DECALS //
{
  uniform uvec4 acessbufferdecals[4096];//use the max amount of memory
};

layout (std140 , binding = 9) uniform Offsets_buffer_DECALS //size of grid
{
  uniform uvec4 offsetsdecals[(16*8*20)];//pack into vec4 for std140
};

layout (std430 , binding = 0) restrict readonly buffer BlueNoise //size of grid
{
   uint g_scrambling_tile_buffer[128*128*8];
};

// Blue Noise Sampler by Eric Heitz. Returns a value in the range [0, 1].
float SampleRandomNumber(uint pixel_i, uint pixel_j, uint sample_index, float sample_dimension) {
    // Wrap arguments
    pixel_i = pixel_i & 127u;
    pixel_j = pixel_j & 127u;
    // sample_index = sample_index & 255u;
    // sample_dimension = sample_dimension & 255u;

    const uint ranked_sample_index = sample_index ^ 0;


    // Fetch value in sequence
    uint value = uint(32.0*(1.0-float(sample_dimension)) + 226.0*float(sample_dimension));//g_sobol_buffer[sample_dimension + ranked_sample_index * 256u];

    // // If the dimension is optimized, xor sequence value based on optimized scrambling
    value = value ^ g_scrambling_tile_buffer[(uint(sample_dimension) ) + (pixel_i + pixel_j * 128u)*8u ];//

    // Convert to float and return
    return (float(value) + 0.5) / 256.0f;
}

vec3 WorldPosFromDepth(vec2 outTexcoord,float depth) {
  float z = depth * 2.0 - 1.0;

  vec4 clipSpacePosition = vec4(outTexcoord * 2.0 - 1.0, z, 1.0);
  vec4 viewSpacePosition = projMatrixInv * clipSpacePosition;

  // Perspective division
  viewSpacePosition /= viewSpacePosition.w;

  vec4 worldSpacePosition = viewMatrixInv * viewSpacePosition;

  return worldSpacePosition.xyz;
}


int when_eq(float x, float y) {
  return  int(1- abs(sign(x - y)));
}
vec2 encode (vec3 n)
{
  return (vec2(atan(n.y,n.x)/3.1415926536, n.z))*vec2(1);
}

vec3 decode (vec2 enc)
{
  vec2 ang = enc;//*2-1;
    vec2 scth = vec2(sin(ang.x * 3.1415926536),cos(ang.x * 3.1415926536));
    vec2 scphi = vec2(sqrt(1.0 - ang.y*ang.y), ang.y);
    return vec3(scth.y*scphi.x, scth.x*scphi.x, scphi.y);
}



vec2 when_ge2(vec2 x, vec2 y) {
  return 1.0 - max(sign(y - x), 0.0);
}



//TODO FIX THIS, GET RID OF SIGN, it will be zero on zero
//https://knarkowicz.wordpress.com/2014/04/16/octahedron-normal-vector-encoding/
//do it liek the website
vec2 OctWrap( vec2 v )
{
    return ( 1.0 - abs( v.yx ) ) * ( sign(when_ge2(v.xy,vec2(0)) - 0.5) );
}


float when_ge(float x, float y) {
  return 1.0 - max(sign(y - x), 0.0);
}


vec2 encodeNormalFinal( vec3 n )
{
    n /= ( abs( n.x ) + abs( n.y ) + abs( n.z ) );
    n.xy = when_ge(n.z,0)*n.xy + (1 - when_ge(n.z,0))*OctWrap(n.xy);
    n.xy = n.xy * 0.5 + 0.5;
    return n.xy;
}

vec3 decodeNormal( vec2 f )
{
    f = f * 2.0 - 1.0;
    vec3 n = vec3( f.x, f.y, 1.0 - abs( f.x ) - abs( f.y ) );
    float t = clamp( -n.z,0,1 );
    n.xy += -sign(when_ge2(n.xy,vec2(0)) - vec2(0.5))*t;
    return normalize( n );
}

mat3 makematrix(vec4 q){
  mat3 m;
    float sqw = q.w*q.w;
    float sqx = q.x*q.x;
    float sqy = q.y*q.y;
    float sqz = q.z*q.z;

    // invs (inverse square length) is only required if quaternion is not already normalised
    float invs = 1 / (sqx + sqy + sqz + sqw);
    m[0][0] = ( sqx - sqy - sqz + sqw)*invs ; // since sqw + sqx + sqy + sqz =1/invs*invs
    m[1][1] = (-sqx + sqy - sqz + sqw)*invs ;
    m[2][2] = (-sqx - sqy + sqz + sqw)*invs ;

    float tmp1 = q.x*q.y;
    float tmp2 = q.z*q.w;
    m[0][1] = 2.0 * (tmp1 + tmp2)*invs ;
    m[1][0] = 2.0 * (tmp1 - tmp2)*invs ;

    tmp1 = q.x*q.z;
    tmp2 = q.y*q.w;
    m[0][2] = 2.0 * (tmp1 - tmp2)*invs ;
    m[2][0] = 2.0 * (tmp1 + tmp2)*invs ;
    tmp1 = q.y*q.z;
    tmp2 = q.x*q.w;
    m[1][2] = 2.0 * (tmp1 + tmp2)*invs ;
    m[2][1] = 2.0 * (tmp1 - tmp2)*invs ;
    return m;
}

// float mip_map_level(in vec2 texture_coordinate)
// {
//     // The OpenGL Graphics System: A Specification 4.2
//     //  - chapter 3.9.11, equation 3.21
//
//
//     vec2  dx_vtc        = dFdx(texture_coordinate);
//     vec2  dy_vtc        = dFdy(texture_coordinate);
//     float delta_max_sqr = max(dot(dx_vtc, dx_vtc), dot(dy_vtc, dy_vtc));
//
//
//     //return max(0.0, 0.5 * log2(delta_max_sqr) - 1.0); // == log2(sqrt(delta_max_sqr));
//     return 0.5 * log2(delta_max_sqr); // == log2(sqrt(delta_max_sqr));
// }

float mip_map_level(vec2 dx_vtc,vec2  dy_vtc)
{
    // The OpenGL Graphics System: A Specification 4.2
    //  - chapter 3.9.11, equation 3.21

    float delta_max_sqr = max(dot(dx_vtc, dx_vtc), dot(dy_vtc, dy_vtc));


    //return max(0.0, 0.5 * log2(delta_max_sqr) - 1.0); // == log2(sqrt(delta_max_sqr));
    return 0.5 * log2(delta_max_sqr); // == log2(sqrt(delta_max_sqr));
}

float when_gt(float x, float y) {
  return max(sign(x - y), 0.0);
}

float when_lt(float x, float y) {
  return max(sign(y - x), 0.0);
}

float when_bounded(vec3 v)
{
  return when_lt(v.x,1)*when_lt(v.y,1)*when_gt(v.x,0)*when_gt(v.y,0)*when_lt(v.z,1)*when_gt(v.z,0);
}

float CheckCollision(vec3 pos, vec3 bmin,vec3 bmax)
{
  return when_lt(pos.x,bmax.x)*when_lt(pos.y,bmax.y)*when_lt(pos.z,bmax.z)*when_gt(pos.x,bmin.x)*when_gt(pos.y,bmin.y)*when_gt(pos.z,bmin.z);
}

float screen2EyeDepth(float depth, float near, float far)
{

    float ndc = 2.0 * depth - 1.0;
    float eye = 2.0 * far * near / (far + near + ndc * (near - far));
    return eye;
}

uint getClusterZIndex(float screenDepth)
{

    float eyeDepth = screen2EyeDepth(screenDepth, zNear, zFar);
    uint zIndex = uint(float(num_slices)*(log(eyeDepth/zNear)/log(zFar/zNear)));
    // uint zIndex = uint(max(log(eyeDepth) * scale + bias, 0.0));
    return zIndex;
}


float isDithered(vec2 pos, float alpha) {


    float DITHER_THRESHOLDS[16] =
    {
        1.0 / 17.0,  9.0 / 17.0,  3.0 / 17.0, 11.0 / 17.0,
        13.0 / 17.0,  5.0 / 17.0, 15.0 / 17.0,  7.0 / 17.0,
        4.0 / 17.0, 12.0 / 17.0,  2.0 / 17.0, 10.0 / 17.0,
        16.0 / 17.0,  8.0 / 17.0, 14.0 / 17.0,  6.0 / 17.0
    };

    int index = (int(pos.x) % 4) * 4 + int(pos.y) % 4;
    return alpha - DITHER_THRESHOLDS[index];
}

#define DXC_STATIC_DISPATCH_GRID_DIM 0

// Divide the 2D-Dispatch_Grid into tiles of dimension [N, DipatchGridDim.y]
// “CTA” (Cooperative Thread Array) == Thread Group in DirectX terminology
uvec2 ThreadGroupTilingX(
	const uvec2 dipatchGridDim,		// Arguments of the Dispatch call (typically from a ConstantBuffer)
	const uvec2 ctaDim,			// Already known in HLSL, eg:[numthreads(8, 8, 1)] -> uint2(8, 8)
	const uint maxTileWidth,		// User parameter (N). Recommended values: 8, 16 or 32.
	const uvec2 groupThreadID,		// SV_GroupThreadID
	const uvec2 groupId			// SV_GroupID
)
{
	// A perfect tile is one with dimensions = [maxTileWidth, dipatchGridDim.y]
	const uint Number_of_CTAs_in_a_perfect_tile = maxTileWidth * dipatchGridDim.y;

	// Possible number of perfect tiles
	const uint Number_of_perfect_tiles = dipatchGridDim.x / maxTileWidth;

	// Total number of CTAs present in the perfect tiles
	const uint Total_CTAs_in_all_perfect_tiles = Number_of_perfect_tiles * maxTileWidth * dipatchGridDim.y;
	const uint vThreadGroupIDFlattened = dipatchGridDim.x * groupId.y + groupId.x;

	// Tile_ID_of_current_CTA : current CTA to TILE-ID mapping.
	const uint Tile_ID_of_current_CTA = vThreadGroupIDFlattened / Number_of_CTAs_in_a_perfect_tile;
	const uint Local_CTA_ID_within_current_tile = vThreadGroupIDFlattened % Number_of_CTAs_in_a_perfect_tile;
	uint Local_CTA_ID_y_within_current_tile;
	uint Local_CTA_ID_x_within_current_tile;

	if (Total_CTAs_in_all_perfect_tiles <= vThreadGroupIDFlattened)
	{
		// Path taken only if the last tile has imperfect dimensions and CTAs from the last tile are launched.
		uint X_dimension_of_last_tile = dipatchGridDim.x % maxTileWidth;
	#ifdef DXC_STATIC_DISPATCH_GRID_DIM
		X_dimension_of_last_tile = max(1, X_dimension_of_last_tile);
	#endif
		Local_CTA_ID_y_within_current_tile = Local_CTA_ID_within_current_tile / X_dimension_of_last_tile;
		Local_CTA_ID_x_within_current_tile = Local_CTA_ID_within_current_tile % X_dimension_of_last_tile;
	}
	else
	{
		Local_CTA_ID_y_within_current_tile = Local_CTA_ID_within_current_tile / maxTileWidth;
		Local_CTA_ID_x_within_current_tile = Local_CTA_ID_within_current_tile % maxTileWidth;
	}

	const uint Swizzled_vThreadGroupIDFlattened =
		Tile_ID_of_current_CTA * maxTileWidth +
		Local_CTA_ID_y_within_current_tile * dipatchGridDim.x +
		Local_CTA_ID_x_within_current_tile;

	uvec2 SwizzledvThreadGroupID;
	SwizzledvThreadGroupID.y = Swizzled_vThreadGroupIDFlattened / dipatchGridDim.x;
	SwizzledvThreadGroupID.x = Swizzled_vThreadGroupIDFlattened % dipatchGridDim.x;

	uvec2 SwizzledvThreadID;
	SwizzledvThreadID.x = ctaDim.x * SwizzledvThreadGroupID.x + groupThreadID.x;
	SwizzledvThreadID.y = ctaDim.y * SwizzledvThreadGroupID.y + groupThreadID.y;

	return SwizzledvThreadID.xy;
}

shared vec2 deriv[GROUP_SIZE_x][GROUP_SIZE_y];

vec3 hash3( vec2 p )
{
    vec3 q = vec3( dot(p,vec2(127.1,311.7)),
				   dot(p,vec2(269.5,183.3)),
				   dot(p,vec2(419.2,371.9)) );
	return fract(sin(q)*43758.5453);
}

void main()
{

  uvec2 global_invoc = ThreadGroupTilingX(uvec2((screenSize.x)/GROUP_SIZE_x,(screenSize.y)/GROUP_SIZE_y),uvec2(GROUP_SIZE_x,GROUP_SIZE_y),8,gl_LocalInvocationID.xy,gl_WorkGroupID.xy);
  // vec3 N_prime = decodeNormal(texture(norInfo,outTexcoord).zw);
  ivec2 pixel_coords = ivec2(global_invoc.xy);
  vec2 outTexcoord = (vec2(pixel_coords)/screenSize) + 0.5/screenSize;

  vec3 ti = texture(texInfo,outTexcoord).xyz;
  float synflag = clamp( 1 - sign(ti.z),0,1);
  ti.z = ti.z - 1*sign(ti.z);
  ti.z = abs(ti.z);


  // float mip = mip_map_level(derFdX,derFdY);
  deriv[gl_LocalInvocationID.x][gl_LocalInvocationID.y] = ti.xy;
//  memoryBarrierShared();

  uvec2 quadIndex = gl_LocalInvocationID.xy/2;
  vec2 derFdX = deriv[1 + quadIndex.x*2][gl_LocalInvocationID.y] - deriv[quadIndex.x*2][gl_LocalInvocationID.y];
  vec2 derFdY = deriv[gl_LocalInvocationID.x][1 + quadIndex.y*2] - deriv[gl_LocalInvocationID.x ][quadIndex.y*2];


  vec4 tangent_normal = texture(norInfo,outTexcoord);
  vec2 sb = tangent_normal.zw;
  vec3 N = normalize(decodeNormal(sb));

  float depthval = texture2D(depthTex,outTexcoord ).r;
  vec3 worldpos = WorldPosFromDepth(outTexcoord,depthval);

  ivec2 tile_id = ivec2((pixel_coords.xy + 0.5/screenSize) / vec2(screenSize.x/16.0,screenSize.y/8.0));
  uint cluster_slice_id = getClusterZIndex(depthval);

  uint tile_index = tile_id.x + tile_id.y*num_tiles_x + cluster_slice_id*num_tiles_x*num_tiles_y;
  uvec2 arr[2];
  arr[0] = offsetsdecals[tile_index/2].xy;
  arr[1] = offsetsdecals[tile_index/2].zw;
  uint count = arr[tile_index%2].y;
  uint offset = arr[tile_index%2].x;

  float inside = 0;
  float decal_id_final = 0;
  vec2 decal_coords_final = vec2(0,0);

  for (int i = 0 ; i < count;i++)
  {
    uint a = offset + i;
    uint key =  acessbufferdecals[a/4][a%4];
    mat4 decal_mat = decals_list[key].decal_matrix;
    float decal_id = decals_list[key].decal_properties.x;
    vec3 decal_normal = decals_list[key].decal_properties.yzw;

    //-- calculate texture coordinates for projection texture.
    vec4 pixelClipPos = decal_mat*vec4(worldpos, 1.0f);
    pixelClipPos.xyz /= pixelClipPos.w;
    pixelClipPos.xyz = pixelClipPos.xyz * 0.5 + 0.5;

    float angle = dot(N, decal_normal);//*CheckCollision(worldpos,vec3(-100,-100,-100),vec3(0,0,0))
    float inside_this = when_lt(angle,-0.1)*when_bounded(pixelClipPos.xyz)*synflag;

    float height = 1;
    if (inside_this == 1)
    {
      height = textureLod(materials,vec3(pixelClipPos.xy,decal_id + 2),7).r;
    }

    //*when_gt(isDithered(global_invoc + vec2(0.5,0.5) ,height),0.0)
    //isDithered(global_invoc + vec2(0.5,0.5) ,height)
    #ifdef BLUE_NOISE
    float blueNoise = SampleRandomNumber(global_invoc.x,global_invoc.y,0,0);
    inside_this = inside_this*when_gt(step(1.0 - height,blueNoise),0);
    #else
    float blueNoise = SampleRandomNumber(global_invoc.x,global_invoc.y,0,0);
    inside_this = inside_this*when_gt(isDithered(global_invoc + vec2(0.5,0.5) ,height),0.0);
    #endif


    inside += inside_this;
    decal_id_final = decal_id_final*(1- inside_this) + decal_id*inside_this;
    decal_coords_final = decal_coords_final*(1- inside_this) + pixelClipPos.xy*inside_this;
  }
  inside= clamp(inside,0,1);
  int bias_lod = int(inside)*-7;

    vec3 decal_info = vec3(mod(decal_coords_final,vec2(1,1)),decal_id_final);

    #ifdef MIX_NORMALS
    vec4 b = textureGrad(materials,vec3(ti.xy,(ti.z + 1)),derFdX,derFdY);
     ti = ti.xyz*vec3((1-inside)) + decal_info*vec3(inside);
    // ti.y = 1 - ti.y;
    derFdX *= 2^(-bias_lod);
    derFdY *= 2^(-bias_lod);

    vec4 decal_normal_b = textureLod(materials,vec3(ti.xy,(ti.z + 1)),7);
    b.xyz = b.xyz * 2.0 - 1.0;
    decal_normal_b.xyz = decal_normal_b.xyz * 2.0 - 1.0;

    decal_normal_b.xyz = normalize(vec3(b.xy + decal_normal_b.xy, b.z*decal_normal_b.z));
    b.xyz = inside*decal_normal_b.xyz + b.xyz*(1 - inside);
    b.w = inside*decal_normal_b.w + b.w*(1 - inside);
    #else
     ti = ti.xyz*vec3((1-inside)) + decal_info*vec3(inside);

     derFdX *= 2^(-bias_lod);
     derFdY *= 2^(-bias_lod);

     vec4 b = textureGrad(materials,vec3(ti.xy,(ti.z + 1)),derFdX,derFdY);
     b.rgb = b.rgb*2.0 - 1.0;
     b.rgb = normalize(b.rgb);
    #endif

  vec4 albedometal = textureGrad(materials,vec3(ti.xy,ti.z),derFdX,derFdY);//*vec4(vec3(synflag),1);
  float ao = textureGrad(materials,vec3(ti.xy,(ti.z + 2)),derFdX,derFdY).r*(when_lt(ti.z - 7.0,0.1)) + 1.0*(1 - when_lt(ti.z - 7.0,0.1));
  imageStore(albedometal_img, pixel_coords, albedometal);
 //

 vec3 normal = b.rgb;//texture(normalMap, outTexcoord).rgb;
 // normal = normal * 2.0 - 1.0;
 // normal = normalize(normal);
 vec2 sa =tangent_normal.xy;


 vec3 T = normalize(decodeNormal(sa));
 // vec3 B = normalize(vec3(inTransform * vec4(inBiTangent, 0.0)));

 vec3 B = cross(N,T);
mat3 TBN = mat3(T, B, N);

  normal = normalize(TBN * normal);
  vec3 normalroughness = vec3(encodeNormalFinal(normal),b.a);
    imageStore(normalroughness_img, pixel_coords, vec4(normalroughness,mix(ao,1.0,0.4)));
}
